config/routes.rb
Rails.application.routes.draw do

  resources :resources do
    get 'listing', :on => :collection
    put :sort, on: :collection
  end

  resources :events do
    get 'mdn_events', :on => :collection
    put :sort, on: :collection
  end
  match 'mdn_events' => 'events#mdn_events', via: :get

  resources :mannerisms do
    get 'man_nerisms', :on => :collection
    put :sort, on: :collection
  end
  match "man_nerisms" => "mannerisms#man_nerisms", via: :get

  resources :jobs do
    get 'jobslisting', :on => :collection
  end
  match "jobslisting" => "jobs#jobslisting", via: :get

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  

  resources :affiliates do
    get 'affiliatechurches', :on => :collection
    put :sort, on: :collection
  end
  match "affiliatechurches" => "affiliates#affiliatechurches", via: :get

  resources :sponsors do
    put :sort, on: :collection
    get :oursponsors, on: :collection
  end
  match "oursponsors" => "sponsors#oursponsors", via: :get

  resources :names

  resources :visitors, path_names: { new: 'contact_us' }
  match "contact_us" => "visitors#new", via: :get
  get 'visitors/acknowledge'

  get 'pages/aboutus'
  match "aboutus" => "pages#aboutus", via: :get

  get 'pages/bootcamp'
  match "bootcamp" => "pages#bootcamp", via: :get
  
  get 'pages/beliefs'
  match "beliefs" => "pages#beliefs", via: :get

  get 'pages/coaches'
  match "coaches" => "pages#coaches", via: :get

  get 'pages/donate'
  match "donate" => "pages#donate", via: :get

  get 'pages/elders'
  match "elders" => "pages#elders", via: :get

  get 'pages/system'
  match "system" => "pages#system", via: :get

  get "pages/curriculum"
  match "curriculum" => "pages#curriculum", via: :get
  match "weapons" => "pages#curriculum", via: :get

  get "pages/leadership_training"
  match "leadership_training" => "pages#leadership_training", via: :get

  get "pages/lesson_sample"
  match "lesson_sample" => "pages#lesson_sample", via: :get

  get "pages/manstat"
  match "manstat" => "pages#manstat", via: :get

  get 'pages/ourstory'
  match "ourstory" => "pages#ourstory", via: :get

  get 'pages/ourfounder'
  match "ourfounder" => "pages#ourfounder", via: :get

  get 'pages/resources'

  get "pages/testimonies"
  match "testimonies" => "pages#testimonies", via: :get

  get "pages/vision"
  match "vision" => "pages#vision", via: :get

  get "pages/my_story"
  match "my_story" => "pages#my_story", via: :get

  get "pages/moty"
  match "moty" => "pages#moty", via: :get

  get 'pages/dbc2017'
  match "dbc2017" => "pages#dbc2017", via: :get

  get 'pages/dbc2018'
  match "dbc2018" => "pages#dbc2018", via: :get

  get 'pages/store'
  match "store" => "pages#store", via: :get

  root 'home#index'

end

app/models/affiliate.rb
class Affiliate < ActiveRecord::Base

	default_scope { order("priority ASC") }
end

app/models/event.rb
class Event < ActiveRecord::Base
	scope :prioritized, -> { order("priority ASC") }

	scope :ongoing, -> { where(repeatable: true) }
	scope :onetime, -> { where(repeatable: false) }

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/mannerism.rb
class Mannerism < ActiveRecord::Base
	  	default_scope { order("priority ASC") }
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	scope :prioritized, -> { order("priority ASC") }
	
	mount_uploaders :attachments, AttachmentUploader
	serialize :attachments, JSON

	mount_uploader :preview, PreviewUploader
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
    mount_uploader :logo, LogoUploader

  	default_scope { order("priority ASC") }

  	scope :gold, -> { where(level: '1') }
  	scope :silver, -> { where(level: '2') }

end

app/models/user.rb
class User < ActiveRecord::Base

  enum role: [:user, :subscriber, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy,  :acknowledge]
  layout "interior"

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        VisitorContact.message_email(@visitor).deliver_later
        VisitorContact.send_message_email(@visitor).deliver_later
        # format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        # format.json { render :show, status: :created, location: @visitor }
        format.html { render :acknowledge, :notice => 'Message was successfully sent.' }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def acknowledge
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :email, :body)
    end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  # Example usage:
  #
  #   image_set_tag_3x "foo_1x.png", alt: "foo"
  #
  # Will assume there is a 2x and 3x version and provide those automagically.
  #
  # Based on https://gist.github.com/mrreynolds/4fc71c8d09646567111f
  def image_set_tag_3x(source, options = {})
    srcset = [ 2, 3 ].map { |num|
      name = source.sub("_1x.", "_#{num}x.")
      "#{path_to_image(name)} #{num}x"
    }.join(", ")

    image_tag(source, options.merge(srcset: srcset))
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/timer_helper.rb
module TimerHelper

	def countdown_to_display
      launch_day = Time.local(2016, 4, 12, 12, 0)
      if Time.now < launch_day
      	return false
      else
      	return true
      end  	
	end

	def audio_card_display
		show_date = Time.local(2017, 4, 3, 12, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

	def audio_card_display_2018
		show_date = Time.local(2018, 4, 24, 12, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

	def event_day_display
		show_date = Time.local(2018, 4, 21, 8, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end
	def day_after_event_display
		show_date = Time.local(2018, 4, 22, 8, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

end

# SC - Use this conditional to show or hide content depending on the Time.local set in this helper
# <% if time_to_display %>
# or
# <% if audio_card_display %>

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html copy.erb
<%= simple_form_for(@visitor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/visitors/_form.html.erb
<%= simple_form_for(@visitor, html: {class: "form-horizontal", role: "form"}) do |f| %>
<!-- <form role="form" > -->
	<div class="form-group">
		<%= f.input :name, input_html: { class: 'form-control', id: 'name' }%>
	</div>
	<div class="form-group">
		<%= f.input :email, input_html: { class: 'form-control', id: 'email' }%>
	</div>
	<div class="form-group">
        <%= f.input :body, label: 'Message', input_html: { class: 'form-control', id: 'message' }%>
	</div>
	<div class="form-group">
	    <%= f.button :submit, input_html: { class: 'btn btn-default', id: 'Send Message' } %>
	</div>
<% end %>

app/views/visitors/acknowledge.html.erb
<div class="container messagebox">
  <div class="row">
    <div class="col-xs-12">

		</br>
		<p id="notice"><%= notice %></p>

		<p class="font24">Thank you. We will read your message and provide a response if one was requested.<p>
			
		<p class="font24">We pray that MDN is providing value to you and your Church.<p>

    </div>
  </div>
</div>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visitors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.name %></td>
        <td><%= visitor.email %></td>
        <td><%= visitor.body %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

app/views/visitors/new.html.erb
<div id="main">
	<!--Breadcrumb Section Start Here-->
	<div class="breadcrumb-section">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<h1>Contact Us</h1>
					<ul class="breadcrumb">
						<li>
							<a href="index.html">Home</a>
						</li>
						<li class="active">
							Contact Us
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!--Breadcrumb Section End Here-->
	<div class="content-wrapper container" id="page-info">
		<div class="row">
			<div class="col-xs-12 col-sm-6 contact-form">
				<div class="col-xs-12" id="success"></div>
				<h2>Send us a Message</h2>
                <%= render 'form' %>
			</div>
			<div class="col-xs-12 col-sm-5 col-sm-offset-1 contact-address">
				<h2>Get in touch</h2>
				<address>
					<span> <strong>Address :</strong> <span>27 Grand Avenue,
							<br>Farmingdale, NY 11735</span> </span>
					<span> <strong>E-Mail :</strong> <span><a href="mailto:info@mensdiscipleshipnetwork.com">info@mensdiscipleshipnetwork.com</a></span> </span>
					<span> <strong>Tel :</strong> <span><a href="tel:+16317531244">+1 631 753 1244</a></span> </span>
					<span> <strong>Fax :</strong> <span>+1 631 753 1245</span> </span>
				</address>
			</div>
		</div>
	</div>
</div>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @visitor.body %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>