config/routes.rb
Rails.application.routes.draw do

  resources :resources do
    get 'listing', :on => :collection
    put :sort, on: :collection
  end

  resources :events do
    get 'mdn_events', :on => :collection
    put :sort, on: :collection
  end
  match 'mdn_events' => 'events#mdn_events', via: :get

  resources :mannerisms do
    get 'man_nerisms', :on => :collection
    put :sort, on: :collection
  end
  match "man_nerisms" => "mannerisms#man_nerisms", via: :get

  resources :jobs do
    get 'jobslisting', :on => :collection
  end
  match "jobslisting" => "jobs#jobslisting", via: :get

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  

  resources :affiliates do
    get 'affiliatechurches', :on => :collection
    put :sort, on: :collection
  end
  match "affiliatechurches" => "affiliates#affiliatechurches", via: :get

  resources :sponsors do
    put :sort, on: :collection
    get :oursponsors, on: :collection
  end
  match "oursponsors" => "sponsors#oursponsors", via: :get

  resources :names

  resources :visitors, path_names: { new: 'contact_us' }
  match "contact_us" => "visitors#new", via: :get
  get 'visitors/acknowledge'

  get 'pages/aboutus'
  match "aboutus" => "pages#aboutus", via: :get

  get 'pages/bootcamp'
  match "bootcamp" => "pages#bootcamp", via: :get
  
  get 'pages/beliefs'
  match "beliefs" => "pages#beliefs", via: :get

  get 'pages/coaches'
  match "coaches" => "pages#coaches", via: :get

  get 'pages/donate'
  match "donate" => "pages#donate", via: :get

  get 'pages/elders'
  match "elders" => "pages#elders", via: :get

  get 'pages/system'
  match "system" => "pages#system", via: :get

  get "pages/curriculum"
  match "curriculum" => "pages#curriculum", via: :get
  match "weapons" => "pages#curriculum", via: :get

  get "pages/leadership_training"
  match "leadership_training" => "pages#leadership_training", via: :get

  get "pages/lesson_sample"
  match "lesson_sample" => "pages#lesson_sample", via: :get

  get "pages/manstat"
  match "manstat" => "pages#manstat", via: :get

  get 'pages/ourstory'
  match "ourstory" => "pages#ourstory", via: :get

  get 'pages/ourfounder'
  match "ourfounder" => "pages#ourfounder", via: :get

  get 'pages/resources'

  get "pages/testimonies"
  match "testimonies" => "pages#testimonies", via: :get

  get "pages/vision"
  match "vision" => "pages#vision", via: :get

  get "pages/my_story"
  match "my_story" => "pages#my_story", via: :get

  get "pages/moty"
  match "moty" => "pages#moty", via: :get

  get 'pages/dbc2017'
  match "dbc2017" => "pages#dbc2017", via: :get

  get 'pages/dbc2018'
  match "dbc2018" => "pages#dbc2018", via: :get

  get 'pages/store'
  match "store" => "pages#store", via: :get

  root 'home#index'

end

app/models/affiliate.rb
class Affiliate < ActiveRecord::Base

	default_scope { order("priority ASC") }
end

app/models/event.rb
class Event < ActiveRecord::Base
	scope :prioritized, -> { order("priority ASC") }

	scope :ongoing, -> { where(repeatable: true) }
	scope :onetime, -> { where(repeatable: false) }

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/mannerism.rb
class Mannerism < ActiveRecord::Base
	  	default_scope { order("priority ASC") }
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	scope :prioritized, -> { order("priority ASC") }
	
	mount_uploaders :attachments, AttachmentUploader
	serialize :attachments, JSON

	mount_uploader :preview, PreviewUploader
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
    mount_uploader :logo, LogoUploader

  	default_scope { order("priority ASC") }

  	scope :gold, -> { where(level: '1') }
  	scope :silver, -> { where(level: '2') }

end

app/models/user.rb
class User < ActiveRecord::Base

  enum role: [:user, :subscriber, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:jobslisting]
  layout 'interior'

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  def jobslisting
    @jobs = Job.where(visible: true)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :volunteer, :visible)
    end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  # Example usage:
  #
  #   image_set_tag_3x "foo_1x.png", alt: "foo"
  #
  # Will assume there is a 2x and 3x version and provide those automagically.
  #
  # Based on https://gist.github.com/mrreynolds/4fc71c8d09646567111f
  def image_set_tag_3x(source, options = {})
    srcset = [ 2, 3 ].map { |num|
      name = source.sub("_1x.", "_#{num}x.")
      "#{path_to_image(name)} #{num}x"
    }.join(", ")

    image_tag(source, options.merge(srcset: srcset))
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/timer_helper.rb
module TimerHelper

	def countdown_to_display
      launch_day = Time.local(2016, 4, 12, 12, 0)
      if Time.now < launch_day
      	return false
      else
      	return true
      end  	
	end

	def audio_card_display
		show_date = Time.local(2017, 4, 3, 12, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

	def audio_card_display_2018
		show_date = Time.local(2018, 4, 24, 12, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

	def event_day_display
		show_date = Time.local(2018, 4, 21, 8, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end
	def day_after_event_display
		show_date = Time.local(2018, 4, 22, 8, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

end

# SC - Use this conditional to show or hide content depending on the Time.local set in this helper
# <% if time_to_display %>
# or
# <% if audio_card_display %>

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :volunteer %>
    <%= f.input :visible %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Volunteer</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.volunteer %></td>
        <td><%= job.visible %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/jobslisting.html.erb
<div class="row">
  <div class="col-xs-1"></div>
    <div class="col-xs-10">
<header><h2>Volunteer with MDN!</h2></header>

<% if @jobs.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Volunteer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.description %></td>
          <td><%= job.volunteer %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% else %>
  <h3>There are no opportunities to volunteer at this time. Please check back again as opportunities open up with over the course of the year. Thank you for your willingness to come alongside us to assist. It is much appreciated!</h3>
</br>
<% end %>
    </div>
  <div class="col-xs-1"></div>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Volunteer:</strong>
  <%= @job.volunteer %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @job.visible %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>