config/routes.rb
Rails.application.routes.draw do

  resources :resources do
    get 'listing', :on => :collection
    put :sort, on: :collection
  end

  resources :events do
    get 'mdn_events', :on => :collection
    put :sort, on: :collection
  end
  match 'mdn_events' => 'events#mdn_events', via: :get

  resources :mannerisms do
    get 'man_nerisms', :on => :collection
    put :sort, on: :collection
  end
  match "man_nerisms" => "mannerisms#man_nerisms", via: :get

  resources :jobs do
    get 'jobslisting', :on => :collection
  end
  match "jobslisting" => "jobs#jobslisting", via: :get

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  

  resources :affiliates do
    get 'affiliatechurches', :on => :collection
    put :sort, on: :collection
  end
  match "affiliatechurches" => "affiliates#affiliatechurches", via: :get

  resources :sponsors do
    put :sort, on: :collection
    get :oursponsors, on: :collection
  end
  match "oursponsors" => "sponsors#oursponsors", via: :get

  resources :names

  resources :visitors, path_names: { new: 'contact_us' }
  match "contact_us" => "visitors#new", via: :get
  get 'visitors/acknowledge'

  get 'pages/aboutus'
  match "aboutus" => "pages#aboutus", via: :get

  get 'pages/bootcamp'
  match "bootcamp" => "pages#bootcamp", via: :get
  
  get 'pages/beliefs'
  match "beliefs" => "pages#beliefs", via: :get

  get 'pages/coaches'
  match "coaches" => "pages#coaches", via: :get

  get 'pages/donate'
  match "donate" => "pages#donate", via: :get

  get 'pages/elders'
  match "elders" => "pages#elders", via: :get

  get 'pages/system'
  match "system" => "pages#system", via: :get

  get "pages/curriculum"
  match "curriculum" => "pages#curriculum", via: :get
  match "weapons" => "pages#curriculum", via: :get

  get "pages/leadership_training"
  match "leadership_training" => "pages#leadership_training", via: :get

  get "pages/lesson_sample"
  match "lesson_sample" => "pages#lesson_sample", via: :get

  get "pages/manstat"
  match "manstat" => "pages#manstat", via: :get

  get 'pages/ourstory'
  match "ourstory" => "pages#ourstory", via: :get

  get 'pages/ourfounder'
  match "ourfounder" => "pages#ourfounder", via: :get

  get 'pages/resources'

  get "pages/testimonies"
  match "testimonies" => "pages#testimonies", via: :get

  get "pages/vision"
  match "vision" => "pages#vision", via: :get

  get "pages/my_story"
  match "my_story" => "pages#my_story", via: :get

  get "pages/moty"
  match "moty" => "pages#moty", via: :get

  get 'pages/dbc2017'
  match "dbc2017" => "pages#dbc2017", via: :get

  get 'pages/dbc2018'
  match "dbc2018" => "pages#dbc2018", via: :get

  get 'pages/store'
  match "store" => "pages#store", via: :get

  root 'home#index'

end

app/models/affiliate.rb
class Affiliate < ActiveRecord::Base

	default_scope { order("priority ASC") }
end

app/models/event.rb
class Event < ActiveRecord::Base
	scope :prioritized, -> { order("priority ASC") }

	scope :ongoing, -> { where(repeatable: true) }
	scope :onetime, -> { where(repeatable: false) }

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/mannerism.rb
class Mannerism < ActiveRecord::Base
	  	default_scope { order("priority ASC") }
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	scope :prioritized, -> { order("priority ASC") }
	
	mount_uploaders :attachments, AttachmentUploader
	serialize :attachments, JSON

	mount_uploader :preview, PreviewUploader
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
    mount_uploader :logo, LogoUploader

  	default_scope { order("priority ASC") }

  	scope :gold, -> { where(level: '1') }
  	scope :silver, -> { where(level: '2') }

end

app/models/user.rb
class User < ActiveRecord::Base

  enum role: [:user, :subscriber, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  # Example usage:
  #
  #   image_set_tag_3x "foo_1x.png", alt: "foo"
  #
  # Will assume there is a 2x and 3x version and provide those automagically.
  #
  # Based on https://gist.github.com/mrreynolds/4fc71c8d09646567111f
  def image_set_tag_3x(source, options = {})
    srcset = [ 2, 3 ].map { |num|
      name = source.sub("_1x.", "_#{num}x.")
      "#{path_to_image(name)} #{num}x"
    }.join(", ")

    image_tag(source, options.merge(srcset: srcset))
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/timer_helper.rb
module TimerHelper

	def countdown_to_display
      launch_day = Time.local(2016, 4, 12, 12, 0)
      if Time.now < launch_day
      	return false
      else
      	return true
      end  	
	end

	def audio_card_display
		show_date = Time.local(2017, 4, 3, 12, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

	def audio_card_display_2018
		show_date = Time.local(2018, 4, 24, 12, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

	def event_day_display
		show_date = Time.local(2018, 4, 21, 8, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end
	def day_after_event_display
		show_date = Time.local(2018, 4, 22, 8, 0)
		if Time.now < show_date
			return false
		else
			return true
		end
	end

end

# SC - Use this conditional to show or hide content depending on the Time.local set in this helper
# <% if time_to_display %>
# or
# <% if audio_card_display %>

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/resources/_form.html.erb
<%= simple_form_for(@resource, html: {multipart: true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>

<!-- Tabs to guide to the right kind of resource -->
	<ul class="nav nav-tabs">
	  <li><a data-toggle="tab" href="#menu1">Video Link</a></li>
	  <li><a data-toggle="tab" href="#menu2">File Attachment</a></li>
	</ul>
	<div class="tab-content">
	  <div id="menu1" class="tab-pane fade">
	  	<h3>Provide a Video URL:</h3>
	  	<label>Provide the full iframe embed code of the Vimeo or YouTube link.</label>
	    <%= f.input :video_url, label: "Vimeo iFrame Code/URL" %>
	  </div>
	  <div id="menu2" class="tab-pane fade">
	  	<h3>Add Attachments:</h3>
		<label>Add one or more attachments. Each will have it's own download button on the Resources page.</label>
	    <%= f.file_field :attachments, multiple: true %></br>
	    <label>Add an image that represents the resource(s) being posted. The image will be resised to 850px x 360px. Your original should be that size or greater.</label>
	    <%= f.file_field :preview %>
        
	    </br>
	    <% if @resource.attachments? %>
	    <h3>Current Attachments:</h3>
	    <label>Note: Removing one attachment will remove all attachments in this resource.</label>
	    <table>
		  	<% @resource.attachments.each do |attachment| %>
		  	    <tr>
		  	    	<td><%= File.basename(attachment.path) %> </td><td><%= f.check_box :remove_attachments %> Remove Attachment </td>
		  	    </tr>
			<% end %>
		</table>
		<% end %>
		
	  </div>
	</div>
<!-- Tabs end -->
  </div>
	<div class="form-actions">
      <%= f.button :submit %>
    </div>
  
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<div class="cause-page content-wrapper" id="page-info">
    <div class="container">
        <div class="anim-section">
          <div class="row">
            <div class="col-xs-12 col-sm-9 left-block event_page">
            <% if @resources.empty? %>
              <div class="event_descriptions">
                <p>There are no resources currently available</p>
              </div>
            <% end %>
            <% @resources.prioritized.each do |resource| %>
                <div class="event_heading clearfix">
                  <div class="event_detail">
                    <% unless resource.video_url.empty? %>
                      <div class="video  video-responsive">
                        <%= resource.video_url.html_safe %>
                      </div>
                    <% else %>
                      <figure>
                        <!-- Image aspect ratio should be 850 x 360 -->
                        <%= image_tag(resource.preview.url) %>
                      </figure>
                    <% end %>
                  </div> 

                  <h2><a href="#"><%= resource.title %></a></h2>         
                  <div class="event_descriptions">
                    <p><%= resource.description %></p> 
                    <% unless resource.attachments.empty? %>     
                      <% resource.attachments.each do |attachment| %>
                        <a href="<%= attachment.url %>" class="btn btn-default" download="<%= File.basename(attachment.path) %>" >Download</a> <%= File.basename(attachment.path) %></br></br>
                      <% end %>
                    <% end %>
                  </div> 
                </div> 
            <% end %> 
          </br>
            <% if user_signed_in? %>
              <%= link_to 'New Resource', new_resource_path %> | 
              <%= link_to 'Resource List', listing_resources_path %>
            <% end %>  
            </div> 
          </div>
        </div>
    </div>
</div>

app/views/resources/listing.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>ID</th>
      <th>Priority</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="resource-sortable">
    <% if @resources.nil? %>
      <p>There are currently no resources</p>
    <% else %>
      <% @resources.prioritized.each do |resource| %>
        <tr class="sortable-row"  data-id="<%= resource.id %>">
          <td><%= resource.title %></td>
          <td><%= resource.description %></td>
          <td><%= resource.id %></td>
          <td><%= resource.priority %></td>
          <td><%= link_to 'Show', resource %></td>
          <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
          <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @resource.video_url %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/shared/_curriculum_slider.html.erb
<section class="rev_slider_wrapper fullwidthbanner-container">
      <div id="rev_slider_14_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="mdn-home-slider1" data-source="gallery" style="margin:0px auto;background-color:#ffffff;padding:0px;margin-top:0px;margin-bottom:0px;">
      <!-- START REVOLUTION SLIDER 5.3.1.6 fullwidth mode -->
            <div id="rev_slider_14_1" class="rev_slider fullwidthabanner tp-overflow-hidden" style="display:none;" data-version="5.3.1.6">
                  <ul>	
                        <!-- SLIDE  -->
                        <%= render "/shared/slides/latino_family_slide" %>
                      
	                  <!-- SLIDE  -->
                        <%= render "/shared/slides/black_family_slide" %>

                        <!-- SLIDE  -->
                        <%= render "/shared/slides/white_family_slide" %>
                  </ul>
            </div>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>	
      </div>
</section>

app/views/shared/_dbc_slider.html.erb
<section class="rev_slider_wrapper fullwidthbanner-container">
      <div id="rev_slider_14_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="mdn-home-slider1" data-source="gallery" style="margin:0px auto;background-color:#ffffff;padding:0px;margin-top:0px;margin-bottom:0px;">
      <!-- START REVOLUTION SLIDER 5.3.1.6 fullwidth mode -->
            <div id="rev_slider_14_1" class="rev_slider fullwidthabanner tp-overflow-hidden" style="display:none;" data-version="5.3.1.6">
                  <ul>	
                        <!-- SLIDE  -->
                        <%= render "/shared/slides/dbc2018_slide" %>
                        <!-- SLIDE  -->
                        <%#= render "/shared/slides/audio_card_slide" %>
	                  <!-- SLIDE  -->
                        <%#= render "/shared/slides/men_praying_slide" %>
                  </ul>
            </div>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>	
      </div>
</section>

app/views/shared/_footer.html.erb
<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-4">
				<div class="footer-logo">
					<a href="/" title="Welcome to Charity"><%= image_tag('logos/mdn_logo_wh_240.png') %></a>
				</div>
				<p>
					MDN is a 501c3 non-profit organization established to set men and their families free from the lies they believe and then live, so they can discover their true purpose for living.
				</p>
				<address>
					<span> <i class="fa fa-home"></i> <span>27 Grand Ave. Farmingdale, NY 11735</span> </span>
					<span> <i class="fa fa-phone-square"></i> <span>+1 631 753 1244</span> </span>
					<span> <i class="fa fa-envelope"></i> <span><a href="mailto:info@mensdiscipleshipnetwork.com">info@mensdiscipleshipnetwork.com</a></span> </span>
				</address>

			</div>
			<div class="col-xs-12 col-sm-4 twitter-update">
				<!-- <h6>Twitter Feed</h6>
				<p>
					<%#= render 'shared/tweets' %>
					<a href="#"> <span class="charity">@mdncoach</span> Various versions have evolved over the years, sometimes by accident, sometimes on purpos. <span class="comment-time">2 hours ago</span> </a>
				</p> -->
				<!-- <p>
					<a href="#"> <span class="charity">@charity</span> Various versions have evolved over the years, sometimes by accident, sometimes on purpos. <span class="comment-time">2 hours ago</span> </a>
				</p> -->
			</div>
			<div class="col-xs-12 col-sm-4">
				<h6>Newsletter Signup</h6>
				<p>Keep informed on MDN events, workshops, and resources.</p>
				<p class="text-left">
					<a data-toggle="modal" href="http://eepurl.com/cdAGvT" class="btn btn-default btn-lg join-today">SUBSCRIBE</a>
				</p>
			</br>
			</br>
				<!-- <form role="form" class="sign-up">

					<div class="input-group">
						<input class="form-control" type="email" placeholder="Email">
						<div class="input-group-addon">
							<input type="submit" class="btn btn-theme" value="Submit">
						</div>
					</div>

				</form> -->

				<h6>Follow us</h6>
				<ul class="social-icons">
					<li>
						<a href="https://www.facebook.com/Manhood4God" target="_blank"><i class="fa fa-facebook"></i></a>
					</li>
					<li>
						<a href="https://vimeo.com/user14644864" target="_blank"><i class="fa fa-vimeo-square"></i></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<span> &copy; Copyright 2014, All Rights Reserved by Men's Discipleship Network.
						</span>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
	<!-- Basic Page Needs -->
	<meta charset="utf-8">
	<title>Men's Discipleship Network</title>
	<meta name="description" content="MDN">
	<meta name="author" content="Steve Cervera">
	
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	
	<!-- Favicons -->
	<link rel="shortcut icon" href="assets/favicon.png">
	<link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css'>

	<!-- Google Analytics - Start -->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-32607130-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>


	  <%= stylesheet_link_tag  'application', media: 'all', debug: true %>
	  <%= csrf_meta_tags %>

app/views/shared/_home_slider.html.erb
<section class="rev_slider_wrapper fullwidthbanner-container">
      <div id="rev_slider_14_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="mdn-home-slider1" data-source="gallery" style="margin:0px auto;background-color:#ffffff;padding:0px;margin-top:0px;margin-bottom:0px;">
      <!-- START REVOLUTION SLIDER 5.3.1.6 fullwidth mode -->
            <div id="rev_slider_14_1" class="rev_slider fullwidthabanner tp-overflow-hidden" style="display:none;" data-version="5.3.1.6">
                  <ul>	
                        <!-- SLIDE  -->
                        <%= render "/shared/slides/mariano_interview_slide" %>

                        <!-- SLIDE  -->
                        <%= render "/shared/slides/mariano_award_slide" %>

                        <!-- SLIDE  -->
                        <%= render "/shared/slides/one_million_slide" %>

                        <!-- SLIDE  -->
                        <%= render "/shared/slides/weapons_slide" %>

                        <!-- SLIDE  -->
                        <%#= render "/shared/slides/audio_card_slide_2018" %>
                        

                  </ul>
            </div>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>	
      </div>
</section>

app/views/shared/_navbar.html.erb
<header id="header">
	<div class="container">
		<div class="row primary-header">
			<a href="/" class="col-xs-12 col-sm-2 brand" title="Welcome to Charity"><%= image_tag('logos/mdn_logo_wh_240.png') %></a>
			<div class="social-links col-xs-12 col-sm-10">
				<!-- <a href="/jobslisting" class="btn btn-default btn-volunteer">BECOME VOLUNTEER</a> -->

				<ul class="social-icons hidden-xs">
					<li>
						<a href="https://www.facebook.com/Manhood4God" target="_blank"><i class="fa fa-facebook"></i></a>
					</li>
					<!-- <li>
						<a href="http://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
					</li>
					<li>
						<a href="http://dribble.com/" target="_blank"><i class="fa fa-linkedin"></i></a>
					</li> -->
					<li>
						<a href="https://vimeo.com/user14644864" target="_blank"><i class="fa fa-vimeo-square"></i></a>
					</li>

				</ul>
			</div>
		</div>
	</div>
	<div class="navbar navbar-default" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<nav>
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="/" class="submenu-icon">Home<span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
					</li>

					<li>
						<a href="javascript:;"  data-toggle="dropdown"  class="submenu-icon">About Us<span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
						<!-- Drop Down  -->

						<div  class="dropdown-menu">
							<ul>
								
								<li>
									<a href="/ourstory">Our Story</a>
								</li>
								<li>
									<a href="/ourfounder">Our Founder</a>
								</li>
								<li>
									<a href="/vision">Mission & Vision</a>
								</li>
								<li>
									<a href="/beliefs">Beliefs</a>
								</li>
								<li>
									<a href="/elders">Elder Board</a>
								</li>
								<li>
									<a href="/coaches">Coaches</a>
								</li>
								<li>
									<a href="/affiliatechurches">Affiliated Churches</a>
								</li>
								<li>
									<a href="/oursponsors">Sponsors</a>
								</li>


							</ul>
						</div>
					</li>
					<li>
						<a href="javascript:;" data-toggle="dropdown" class="submenu-icon">What We Do<span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
						<!-- Drop Down  -->
						<div  class="dropdown-menu">
							<ul>
								<li>
									<a href="/system">The System</a>
								</li>
								<li>
									<a href="/curriculum">Curriculum</a>
								</li>
								<li>
									<a href="/bootcamp">Discipleship Boot Camp</a>
								</li>
								<li>
									<a href="/leadership_training">Leadership Training</a>
								</li>
								<!-- <li>
									<a href="portfolio-detail.html">Retreats</a>
								</li> -->
								<li>
									<a href="/testimonies">Testimonies</a>
								</li>
							</ul>
						</div>
					</li>
					<li>
						<a href="javascript:;" data-toggle="dropdown" class="submenu-icon">About Men<span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
						<!-- Drop Down  -->
						<div  class="dropdown-menu">
							<ul>
								<li>
									<a href="/manstat">Man-Stats</a>
								</li>
								<li>
									<a href="/man_nerisms">Man-nerisms</a>
								</li>
								<li>
									<a href="http://mdn.christianbook.com/page/tcg/mdn/top-25-books-for-men?event=MDN004">Books About Men</a>
								</li>
								<li>
									<a href="/moty">Man of the Year</a>
								</li>
								<!-- <li>
									<a href="volunteer.html">Man-life Parables</a>
								</li> -->
							</ul>
						</div>
						<!-- end  -->

					</li>
					
					<li>
						<a href="javascript:;" data-toggle="dropdown" class="submenu-icon">Events<span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
	                        <div  class="dropdown-menu">
								<ul>
									<li>
										<a href="/bootcamp">Discipleship Boot Camp</a>
									</li>
									<li>
										<a href="/mdn_events">Schedule of Events</a>
									</li>
								</ul>
							</div>
					</li>
					<li>
						<a href="javascript:;" data-toggle="dropdown" class="submenu-icon">Resources <span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
						<!-- Drop Down  -->
						<div  class="dropdown-menu">
							<ul>
								<li>
									<a href="/store">Store</a>
								</li>
								<li>
									<a href="/curriculum">Men's Curriculum</a>
								</li>
								<li>
									<a href="/dbc2018">DBC 2018 Audio Recording</a>
								</li>
								<li>
									<a href="/dbc2017">DBC 2017 Audio Recording</a>
								</li>
								<li>
									<a href="/resources">Free Coaching Resources</a>
								</li>
								<li>
									<a href="http://mdn.christianbook.com/page/tcg/mdn/top-25-books-for-men?event=MDN004" target="_blank">Top 25 Books For Men</a>
								</li>
<!-- 								<li>
									<a href="blog-full-width-details.html">Video Library</a>
								</li> -->
<!--   								<li>
						            <a href="contact-us.html">Photo Gallery</a>
					            </li> -->
							</ul>
						</div>
					</li>
					<li>
						<a href="javascript:;" data-toggle="dropdown" class="submenu-icon">Help Us<span class="glyphicon glyphicon-chevron-down"></span> <span class="glyphicon glyphicon-chevron-up"></span> </a>
						<!-- Drop Down  -->
						<div  class="dropdown-menu">
							<ul>
								<li>
									<a href="/donate">Donate</a>
								</li>
								<li>
									<a href="/oursponsors">Our Sponsors</a>
								</li>
								<li>
									<a href="/jobslisting">Volunteer</a>
								</li>
							</ul>
						</div>
						<!-- end  -->

					</li>
					<li>
						<a href="/contact_us">Contact Us</a>
					</li>
					<% if user_signed_in? %>
						<li>
							<%= render 'devise/menu/login_items' %>
						</li>
					<% end %>
                    
				</ul>

				</nav>
				
				<!-- <form class="navbar-form navbar-right search-form" role="search">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search Here">
					</div>
					<button type="submit">
						<i class="icon-search"></i>
					</button>
				</form> -->

			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</div>

</header>
		<% if flash[:alert] %>
			<p class="notice"><%= notice %></p>
		    <p class="alert"><%= alert %></p>
		<% end %>

app/views/shared/_tweets.html.erb
# app/views/shared/_tweets.html.haml
<section id="tweets">
  <ul>
    <% @tweets.each do |tweet| %>
      <li> <%= link_to tweet.text, "https://www.twitter.com/#{tweet.user.screen_name}" %> </li>
    <% end %>

  </ul>
</section>